// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: protobuf/common.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_START        CommandType = 0
	CommandType_STOP         CommandType = 1
	CommandType_SET_POSITION CommandType = 2
	CommandType_GET_POSITION CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "SET_POSITION",
		3: "GET_POSITION",
	}
	CommandType_value = map[string]int32{
		"START":        0,
		"STOP":         1,
		"SET_POSITION": 2,
		"GET_POSITION": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_common_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_protobuf_common_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_common_proto_rawDescGZIP(), []int{0}
}

type RobotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.CommandType" json:"type,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotCommand) Reset() {
	*x = RobotCommand{}
	mi := &file_protobuf_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotCommand) ProtoMessage() {}

func (x *RobotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotCommand.ProtoReflect.Descriptor instead.
func (*RobotCommand) Descriptor() ([]byte, []int) {
	return file_protobuf_common_proto_rawDescGZIP(), []int{0}
}

func (x *RobotCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_START
}

func (x *RobotCommand) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotCommand) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RobotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotResponse) Reset() {
	*x = RobotResponse{}
	mi := &file_protobuf_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotResponse) ProtoMessage() {}

func (x *RobotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotResponse.ProtoReflect.Descriptor instead.
func (*RobotResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_common_proto_rawDescGZIP(), []int{1}
}

func (x *RobotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RobotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RobotResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_protobuf_common_proto protoreflect.FileDescriptor

var file_protobuf_common_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4f, 0x0a, 0x0c, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x5f, 0x0a, 0x0d,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x2a, 0x46, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x75, 0x72, 0x74, 0x6c, 0x65, 0x73,
	0x69, 0x6d, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_common_proto_rawDescOnce sync.Once
	file_protobuf_common_proto_rawDescData []byte
)

func file_protobuf_common_proto_rawDescGZIP() []byte {
	file_protobuf_common_proto_rawDescOnce.Do(func() {
		file_protobuf_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_common_proto_rawDesc), len(file_protobuf_common_proto_rawDesc)))
	})
	return file_protobuf_common_proto_rawDescData
}

var file_protobuf_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_common_proto_goTypes = []any{
	(CommandType)(0),      // 0: pb.CommandType
	(*RobotCommand)(nil),  // 1: pb.RobotCommand
	(*RobotResponse)(nil), // 2: pb.RobotResponse
}
var file_protobuf_common_proto_depIdxs = []int32{
	0, // 0: pb.RobotCommand.type:type_name -> pb.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_common_proto_init() }
func file_protobuf_common_proto_init() {
	if File_protobuf_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_common_proto_rawDesc), len(file_protobuf_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_common_proto_goTypes,
		DependencyIndexes: file_protobuf_common_proto_depIdxs,
		EnumInfos:         file_protobuf_common_proto_enumTypes,
		MessageInfos:      file_protobuf_common_proto_msgTypes,
	}.Build()
	File_protobuf_common_proto = out.File
	file_protobuf_common_proto_goTypes = nil
	file_protobuf_common_proto_depIdxs = nil
}
