// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: server/protobuf/robot.proto

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotService_Connect_FullMethodName = "/pb.RobotService/Connect"
)

// RobotServiceClient is the client API for RobotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotMessage, RobotMessage], error)
}

type robotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotServiceClient(cc grpc.ClientConnInterface) RobotServiceClient {
	return &robotServiceClient{cc}
}

func (c *robotServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotMessage, RobotMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotService_ServiceDesc.Streams[0], RobotService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RobotMessage, RobotMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotService_ConnectClient = grpc.BidiStreamingClient[RobotMessage, RobotMessage]

// RobotServiceServer is the server API for RobotService service.
// All implementations must embed UnimplementedRobotServiceServer
// for forward compatibility.
type RobotServiceServer interface {
	Connect(grpc.BidiStreamingServer[RobotMessage, RobotMessage]) error
	mustEmbedUnimplementedRobotServiceServer()
}

// UnimplementedRobotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotServiceServer struct{}

func (UnimplementedRobotServiceServer) Connect(grpc.BidiStreamingServer[RobotMessage, RobotMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRobotServiceServer) mustEmbedUnimplementedRobotServiceServer() {}
func (UnimplementedRobotServiceServer) testEmbeddedByValue()                      {}

// UnsafeRobotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotServiceServer will
// result in compilation errors.
type UnsafeRobotServiceServer interface {
	mustEmbedUnimplementedRobotServiceServer()
}

func RegisterRobotServiceServer(s grpc.ServiceRegistrar, srv RobotServiceServer) {
	// If the following call pancis, it indicates UnimplementedRobotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotService_ServiceDesc, srv)
}

func _RobotService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RobotServiceServer).Connect(&grpc.GenericServerStream[RobotMessage, RobotMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotService_ConnectServer = grpc.BidiStreamingServer[RobotMessage, RobotMessage]

// RobotService_ServiceDesc is the grpc.ServiceDesc for RobotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RobotService",
	HandlerType: (*RobotServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RobotService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/protobuf/robot.proto",
}

const (
	CommandService_Start_FullMethodName       = "/pb.CommandService/Start"
	CommandService_Stop_FullMethodName        = "/pb.CommandService/Stop"
	CommandService_SetPosition_FullMethodName = "/pb.CommandService/SetPosition"
	CommandService_GetPosition_FullMethodName = "/pb.CommandService/GetPosition"
	CommandService_ListRobots_FullMethodName  = "/pb.CommandService/ListRobots"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	Start(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error)
	Stop(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error)
	SetPosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*RobotResponse, error)
	GetPosition(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error)
	ListRobots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RobotListResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) Start(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotResponse)
	err := c.cc.Invoke(ctx, CommandService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) Stop(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotResponse)
	err := c.cc.Invoke(ctx, CommandService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SetPosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*RobotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotResponse)
	err := c.cc.Invoke(ctx, CommandService_SetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetPosition(ctx context.Context, in *RobotCommandRequest, opts ...grpc.CallOption) (*RobotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotResponse)
	err := c.cc.Invoke(ctx, CommandService_GetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ListRobots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RobotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotListResponse)
	err := c.cc.Invoke(ctx, CommandService_ListRobots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
type CommandServiceServer interface {
	Start(context.Context, *RobotCommandRequest) (*RobotResponse, error)
	Stop(context.Context, *RobotCommandRequest) (*RobotResponse, error)
	SetPosition(context.Context, *PositionRequest) (*RobotResponse, error)
	GetPosition(context.Context, *RobotCommandRequest) (*RobotResponse, error)
	ListRobots(context.Context, *emptypb.Empty) (*RobotListResponse, error)
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) Start(context.Context, *RobotCommandRequest) (*RobotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedCommandServiceServer) Stop(context.Context, *RobotCommandRequest) (*RobotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCommandServiceServer) SetPosition(context.Context, *PositionRequest) (*RobotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPosition not implemented")
}
func (UnimplementedCommandServiceServer) GetPosition(context.Context, *RobotCommandRequest) (*RobotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedCommandServiceServer) ListRobots(context.Context, *emptypb.Empty) (*RobotListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRobots not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).Start(ctx, req.(*RobotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).Stop(ctx, req.(*RobotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SetPosition(ctx, req.(*PositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetPosition(ctx, req.(*RobotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ListRobots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ListRobots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_ListRobots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ListRobots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _CommandService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CommandService_Stop_Handler,
		},
		{
			MethodName: "SetPosition",
			Handler:    _CommandService_SetPosition_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _CommandService_GetPosition_Handler,
		},
		{
			MethodName: "ListRobots",
			Handler:    _CommandService_ListRobots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/protobuf/robot.proto",
}
