// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: protobuf/robot_service.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_protobuf_robot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_robot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_protobuf_robot_service_proto_rawDescGZIP(), []int{0}
}

func (x *Registration) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type RobotMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RobotMessage_Registration
	//	*RobotMessage_Command
	//	*RobotMessage_Response
	Payload       isRobotMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotMessage) Reset() {
	*x = RobotMessage{}
	mi := &file_protobuf_robot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotMessage) ProtoMessage() {}

func (x *RobotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_robot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotMessage.ProtoReflect.Descriptor instead.
func (*RobotMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_robot_service_proto_rawDescGZIP(), []int{1}
}

func (x *RobotMessage) GetPayload() isRobotMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RobotMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *RobotMessage) GetCommand() *RobotCommand {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *RobotMessage) GetResponse() *RobotResponse {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isRobotMessage_Payload interface {
	isRobotMessage_Payload()
}

type RobotMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type RobotMessage_Command struct {
	Command *RobotCommand `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type RobotMessage_Response struct {
	Response *RobotResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*RobotMessage_Registration) isRobotMessage_Payload() {}

func (*RobotMessage_Command) isRobotMessage_Payload() {}

func (*RobotMessage_Response) isRobotMessage_Payload() {}

var File_protobuf_robot_service_proto protoreflect.FileDescriptor

var file_protobuf_robot_service_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0c, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x41, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x75,
	0x72, 0x74, 0x6c, 0x65, 0x73, 0x69, 0x6d, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_protobuf_robot_service_proto_rawDescOnce sync.Once
	file_protobuf_robot_service_proto_rawDescData []byte
)

func file_protobuf_robot_service_proto_rawDescGZIP() []byte {
	file_protobuf_robot_service_proto_rawDescOnce.Do(func() {
		file_protobuf_robot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_robot_service_proto_rawDesc), len(file_protobuf_robot_service_proto_rawDesc)))
	})
	return file_protobuf_robot_service_proto_rawDescData
}

var file_protobuf_robot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_robot_service_proto_goTypes = []any{
	(*Registration)(nil),  // 0: pb.Registration
	(*RobotMessage)(nil),  // 1: pb.RobotMessage
	(*RobotCommand)(nil),  // 2: pb.RobotCommand
	(*RobotResponse)(nil), // 3: pb.RobotResponse
}
var file_protobuf_robot_service_proto_depIdxs = []int32{
	0, // 0: pb.RobotMessage.registration:type_name -> pb.Registration
	2, // 1: pb.RobotMessage.command:type_name -> pb.RobotCommand
	3, // 2: pb.RobotMessage.response:type_name -> pb.RobotResponse
	1, // 3: pb.RobotService.Connect:input_type -> pb.RobotMessage
	1, // 4: pb.RobotService.Connect:output_type -> pb.RobotMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_robot_service_proto_init() }
func file_protobuf_robot_service_proto_init() {
	if File_protobuf_robot_service_proto != nil {
		return
	}
	file_protobuf_common_proto_init()
	file_protobuf_robot_service_proto_msgTypes[1].OneofWrappers = []any{
		(*RobotMessage_Registration)(nil),
		(*RobotMessage_Command)(nil),
		(*RobotMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_robot_service_proto_rawDesc), len(file_protobuf_robot_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_robot_service_proto_goTypes,
		DependencyIndexes: file_protobuf_robot_service_proto_depIdxs,
		MessageInfos:      file_protobuf_robot_service_proto_msgTypes,
	}.Build()
	File_protobuf_robot_service_proto = out.File
	file_protobuf_robot_service_proto_goTypes = nil
	file_protobuf_robot_service_proto_depIdxs = nil
}
