// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: server/protobuf/robot.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_START        CommandType = 0
	CommandType_STOP         CommandType = 1
	CommandType_SET_POSITION CommandType = 2
	CommandType_GET_POSITION CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "SET_POSITION",
		3: "GET_POSITION",
	}
	CommandType_value = map[string]int32{
		"START":        0,
		"STOP":         1,
		"SET_POSITION": 2,
		"GET_POSITION": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_protobuf_robot_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_server_protobuf_robot_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{0}
}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_server_protobuf_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{0}
}

func (x *Registration) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type RobotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.CommandType" json:"type,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotCommand) Reset() {
	*x = RobotCommand{}
	mi := &file_server_protobuf_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotCommand) ProtoMessage() {}

func (x *RobotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotCommand.ProtoReflect.Descriptor instead.
func (*RobotCommand) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{1}
}

func (x *RobotCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_START
}

func (x *RobotCommand) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotCommand) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RobotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotResponse) Reset() {
	*x = RobotResponse{}
	mi := &file_server_protobuf_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotResponse) ProtoMessage() {}

func (x *RobotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotResponse.ProtoReflect.Descriptor instead.
func (*RobotResponse) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{2}
}

func (x *RobotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RobotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RobotResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RobotCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotCommandRequest) Reset() {
	*x = RobotCommandRequest{}
	mi := &file_server_protobuf_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotCommandRequest) ProtoMessage() {}

func (x *RobotCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotCommandRequest.ProtoReflect.Descriptor instead.
func (*RobotCommandRequest) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{3}
}

func (x *RobotCommandRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type PositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionRequest) Reset() {
	*x = PositionRequest{}
	mi := &file_server_protobuf_robot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionRequest) ProtoMessage() {}

func (x *PositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionRequest.ProtoReflect.Descriptor instead.
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{4}
}

func (x *PositionRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *PositionRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PositionRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RobotMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RobotMessage_Registration
	//	*RobotMessage_Command
	//	*RobotMessage_Response
	Payload       isRobotMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotMessage) Reset() {
	*x = RobotMessage{}
	mi := &file_server_protobuf_robot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotMessage) ProtoMessage() {}

func (x *RobotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotMessage.ProtoReflect.Descriptor instead.
func (*RobotMessage) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{5}
}

func (x *RobotMessage) GetPayload() isRobotMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RobotMessage) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *RobotMessage) GetCommand() *RobotCommand {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *RobotMessage) GetResponse() *RobotResponse {
	if x != nil {
		if x, ok := x.Payload.(*RobotMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isRobotMessage_Payload interface {
	isRobotMessage_Payload()
}

type RobotMessage_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type RobotMessage_Command struct {
	Command *RobotCommand `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type RobotMessage_Response struct {
	Response *RobotResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*RobotMessage_Registration) isRobotMessage_Payload() {}

func (*RobotMessage_Command) isRobotMessage_Payload() {}

func (*RobotMessage_Response) isRobotMessage_Payload() {}

type RobotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotIds      []string               `protobuf:"bytes,1,rep,name=robot_ids,json=robotIds,proto3" json:"robot_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotListResponse) Reset() {
	*x = RobotListResponse{}
	mi := &file_server_protobuf_robot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotListResponse) ProtoMessage() {}

func (x *RobotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_robot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotListResponse.ProtoReflect.Descriptor instead.
func (*RobotListResponse) Descriptor() ([]byte, []int) {
	return file_server_protobuf_robot_proto_rawDescGZIP(), []int{6}
}

func (x *RobotListResponse) GetRobotIds() []string {
	if x != nil {
		return x.RobotIds
	}
	return nil
}

var File_server_protobuf_robot_proto protoreflect.FileDescriptor

var file_server_protobuf_robot_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0c, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x5f, 0x0a, 0x0d, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x30, 0x0a, 0x13, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x48, 0x0a,
	0x0f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2f,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x30, 0x0a, 0x11, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x73, 0x2a, 0x46, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x03, 0x32, 0x41, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x32, 0xa8, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_server_protobuf_robot_proto_rawDescOnce sync.Once
	file_server_protobuf_robot_proto_rawDescData []byte
)

func file_server_protobuf_robot_proto_rawDescGZIP() []byte {
	file_server_protobuf_robot_proto_rawDescOnce.Do(func() {
		file_server_protobuf_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_protobuf_robot_proto_rawDesc), len(file_server_protobuf_robot_proto_rawDesc)))
	})
	return file_server_protobuf_robot_proto_rawDescData
}

var file_server_protobuf_robot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_protobuf_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_protobuf_robot_proto_goTypes = []any{
	(CommandType)(0),            // 0: pb.CommandType
	(*Registration)(nil),        // 1: pb.Registration
	(*RobotCommand)(nil),        // 2: pb.RobotCommand
	(*RobotResponse)(nil),       // 3: pb.RobotResponse
	(*RobotCommandRequest)(nil), // 4: pb.RobotCommandRequest
	(*PositionRequest)(nil),     // 5: pb.PositionRequest
	(*RobotMessage)(nil),        // 6: pb.RobotMessage
	(*RobotListResponse)(nil),   // 7: pb.RobotListResponse
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_server_protobuf_robot_proto_depIdxs = []int32{
	0,  // 0: pb.RobotCommand.type:type_name -> pb.CommandType
	1,  // 1: pb.RobotMessage.registration:type_name -> pb.Registration
	2,  // 2: pb.RobotMessage.command:type_name -> pb.RobotCommand
	3,  // 3: pb.RobotMessage.response:type_name -> pb.RobotResponse
	6,  // 4: pb.RobotService.Connect:input_type -> pb.RobotMessage
	4,  // 5: pb.CommandService.Start:input_type -> pb.RobotCommandRequest
	4,  // 6: pb.CommandService.Stop:input_type -> pb.RobotCommandRequest
	5,  // 7: pb.CommandService.SetPosition:input_type -> pb.PositionRequest
	4,  // 8: pb.CommandService.GetPosition:input_type -> pb.RobotCommandRequest
	8,  // 9: pb.CommandService.ListRobots:input_type -> google.protobuf.Empty
	6,  // 10: pb.RobotService.Connect:output_type -> pb.RobotMessage
	3,  // 11: pb.CommandService.Start:output_type -> pb.RobotResponse
	3,  // 12: pb.CommandService.Stop:output_type -> pb.RobotResponse
	3,  // 13: pb.CommandService.SetPosition:output_type -> pb.RobotResponse
	3,  // 14: pb.CommandService.GetPosition:output_type -> pb.RobotResponse
	7,  // 15: pb.CommandService.ListRobots:output_type -> pb.RobotListResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_protobuf_robot_proto_init() }
func file_server_protobuf_robot_proto_init() {
	if File_server_protobuf_robot_proto != nil {
		return
	}
	file_server_protobuf_robot_proto_msgTypes[5].OneofWrappers = []any{
		(*RobotMessage_Registration)(nil),
		(*RobotMessage_Command)(nil),
		(*RobotMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_protobuf_robot_proto_rawDesc), len(file_server_protobuf_robot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_protobuf_robot_proto_goTypes,
		DependencyIndexes: file_server_protobuf_robot_proto_depIdxs,
		EnumInfos:         file_server_protobuf_robot_proto_enumTypes,
		MessageInfos:      file_server_protobuf_robot_proto_msgTypes,
	}.Build()
	File_server_protobuf_robot_proto = out.File
	file_server_protobuf_robot_proto_goTypes = nil
	file_server_protobuf_robot_proto_depIdxs = nil
}
