# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protobuf/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobuf/common.proto\x12\x02pb\"C\n\x0cRobotCommand\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.pb.CommandType\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"G\n\rRobotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02*F\n\x0b\x43ommandType\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x10\n\x0cSET_POSITION\x10\x02\x12\x10\n\x0cGET_POSITION\x10\x03\x42\x1eZ\x1cturtlesim-grpc/server/modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034turtlesim-grpc/server/models'
  _globals['_COMMANDTYPE']._serialized_start=171
  _globals['_COMMANDTYPE']._serialized_end=241
  _globals['_ROBOTCOMMAND']._serialized_start=29
  _globals['_ROBOTCOMMAND']._serialized_end=96
  _globals['_ROBOTRESPONSE']._serialized_start=98
  _globals['_ROBOTRESPONSE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
