# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/command_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protobuf/command_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protobuf import common_pb2 as protobuf_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotobuf/command_service.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15protobuf/common.proto\"\'\n\x13RobotCommandRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\"9\n\x0fPositionRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"&\n\x11RobotListResponse\x12\x11\n\trobot_ids\x18\x01 \x03(\t2\xa8\x02\n\x0e\x43ommandService\x12\x33\n\x05Start\x12\x17.pb.RobotCommandRequest\x1a\x11.pb.RobotResponse\x12\x32\n\x04Stop\x12\x17.pb.RobotCommandRequest\x1a\x11.pb.RobotResponse\x12\x35\n\x0bSetPosition\x12\x13.pb.PositionRequest\x1a\x11.pb.RobotResponse\x12\x39\n\x0bGetPosition\x12\x17.pb.RobotCommandRequest\x1a\x11.pb.RobotResponse\x12;\n\nListRobots\x12\x16.google.protobuf.Empty\x1a\x15.pb.RobotListResponseB\x1eZ\x1cturtlesim-grpc/server/modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.command_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034turtlesim-grpc/server/models'
  _globals['_ROBOTCOMMANDREQUEST']._serialized_start=90
  _globals['_ROBOTCOMMANDREQUEST']._serialized_end=129
  _globals['_POSITIONREQUEST']._serialized_start=131
  _globals['_POSITIONREQUEST']._serialized_end=188
  _globals['_ROBOTLISTRESPONSE']._serialized_start=190
  _globals['_ROBOTLISTRESPONSE']._serialized_end=228
  _globals['_COMMANDSERVICE']._serialized_start=231
  _globals['_COMMANDSERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
