# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protobuf import command_service_pb2 as protobuf_dot_command__service__pb2
from protobuf import common_pb2 as protobuf_dot_common__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuf/command_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/pb.CommandService/Start',
                request_serializer=protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
                response_deserializer=protobuf_dot_common__pb2.RobotResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/pb.CommandService/Stop',
                request_serializer=protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
                response_deserializer=protobuf_dot_common__pb2.RobotResponse.FromString,
                _registered_method=True)
        self.SetPosition = channel.unary_unary(
                '/pb.CommandService/SetPosition',
                request_serializer=protobuf_dot_command__service__pb2.PositionRequest.SerializeToString,
                response_deserializer=protobuf_dot_common__pb2.RobotResponse.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/pb.CommandService/GetPosition',
                request_serializer=protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
                response_deserializer=protobuf_dot_common__pb2.RobotResponse.FromString,
                _registered_method=True)
        self.ListRobots = channel.unary_unary(
                '/pb.CommandService/ListRobots',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protobuf_dot_command__service__pb2.RobotListResponse.FromString,
                _registered_method=True)


class CommandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRobots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=protobuf_dot_command__service__pb2.RobotCommandRequest.FromString,
                    response_serializer=protobuf_dot_common__pb2.RobotResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=protobuf_dot_command__service__pb2.RobotCommandRequest.FromString,
                    response_serializer=protobuf_dot_common__pb2.RobotResponse.SerializeToString,
            ),
            'SetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPosition,
                    request_deserializer=protobuf_dot_command__service__pb2.PositionRequest.FromString,
                    response_serializer=protobuf_dot_common__pb2.RobotResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=protobuf_dot_command__service__pb2.RobotCommandRequest.FromString,
                    response_serializer=protobuf_dot_common__pb2.RobotResponse.SerializeToString,
            ),
            'ListRobots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRobots,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protobuf_dot_command__service__pb2.RobotListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.CommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.CommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.CommandService/Start',
            protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
            protobuf_dot_common__pb2.RobotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.CommandService/Stop',
            protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
            protobuf_dot_common__pb2.RobotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.CommandService/SetPosition',
            protobuf_dot_command__service__pb2.PositionRequest.SerializeToString,
            protobuf_dot_common__pb2.RobotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.CommandService/GetPosition',
            protobuf_dot_command__service__pb2.RobotCommandRequest.SerializeToString,
            protobuf_dot_common__pb2.RobotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRobots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.CommandService/ListRobots',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protobuf_dot_command__service__pb2.RobotListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
