services:
  server:
    build: ./turtlesim-grpc
    container_name: server
    ports:
      - "50051:50051"

  robot1:
    build: ./robot
    container_name: robot1
    environment:
      - ROBOT_ID=robot1
      - SERVER_ADDRESS=server:50051
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - server

  robot2:
    build: ./robot
    container_name: robot2
    environment:
      - ROBOT_ID=robot2
      - SERVER_ADDRESS=server:50051
      - ROS_DOMAIN_ID=2
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - server
