services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - robot1
      - robot2

  robot1:
    build: ./robot
    container_name: robot1
    environment:
      - ROBOT_ID=robot1
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5001:50051"

  robot2:
    build: ./robot
    container_name: robot2
    environment:
      - ROBOT_ID=robot2
      - ROS_DOMAIN_ID=2
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5002:50051"
